spring:
  application:
    name: numbers-store
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    testOnBorrow: true
    validationQuery: SELECT 1
    url: jdbc:h2:mem:store;DB_CLOSE_ON_EXIT=FALSE
    username: root
    password: root
    sqlScriptEncoding: UTF-8
    driver-class-name: org.h2.Driver
    type: com.zaxxer.hikari.HikariDataSource

  jpa:
    generate-ddl: true
    database: default
    show-sql: true

  server:
    port: 8080

  jackson:
    serialization-inclusion: NON_EMPTY
    serialization:
      indent_output: true
      write-dates-as-timestamps: false
    property-naming-strategy: SNAKE_CASE

logging.level: INFO
logging.level.org.springframework.web: DEBUG
